### PR TITLE
API 630 support

### PR DESCRIPTION
**Pull request by ex3ndr**

### CODE REVIEW

**Comment by josephg** [comment]
Nice, thanks!

**Comment by josephg** [comment]
(Looks like I forgot to disable appveyor when I moved CI to GitHub actions. Ignore that!)

**Comment by ex3ndr** [comment]
Hey! I think i forgot to bump max supported version

**Comment by josephg** [comment]
Oops! Want to fix that and I'll re-publish? You'll need a new PR.

**Pull request merged**
